server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: ventas-libros

  datasource:
    url: jdbc:postgresql://db.scwfwapgdacnabkbcqdp.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: XmhI0BKUq0knFSQ6sgreTyXP
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

app:
  jwt:
    secret: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
    expiration-ms: 86400000
